version: "3"

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb-pizzeria
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=alex0
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=my_alex0
      # - MYSQL_ROOT_HOST=192.168.0.0/255.255.255.0

  php-fpm:
    image: bitnami/php-fpm:latest
    container_name: php-pizzeria
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www/html

  web:
    image: nginx:latest
    container_name: nginx-pizzeria
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    links:
      - php-fpm
    depends_on:
      - mariadb
      - php-fpm